# Generated by Django 4.2.6 on 2023-11-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=5)),
                ('validade', models.DateField()),
                ('bandeira', models.CharField(max_length=20)),
                ('situacao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cartao',
                'verbose_name_plural': 'Cartoes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('social_fantasia', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('usuario', models.CharField(max_length=10)),
                ('senha', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateField(auto_now=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.FloatField()),
                ('aprovado', models.BooleanField()),
                ('numero_parcela', models.IntegerField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(max_length=200)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=75)),
                ('cidade', models.CharField(max_length=75)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('operacao', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartao')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_adm', models.FloatField()),
                ('prazo', models.CharField(max_length=20)),
                ('grau_risco', models.CharField(max_length=5)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finalizado', models.BooleanField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParcela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emprestimo')),
            ],
            options={
                'verbose_name': 'EmprestimoParcela',
                'verbose_name_plural': 'EmprestimosParcelas',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=15)),
                ('ramal', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('observacao', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=25)),
                ('inscricao_estadual', models.CharField(max_length=30)),
                ('inscricao_municipal', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'ClientePJ',
                'verbose_name_plural': 'ClientesPJ',
            },
        ),
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'ClientePF',
                'verbose_name_plural': 'ClientesPF',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta'),
        ),
    ]
