# Generated by Django 4.2.6 on 2023-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clientepf_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
