# Generated by Django 4.2.6 on 2023-11-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartao_numero_alter_conta_limite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='id_conta',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='social_fantasia',
            new_name='nome',
        ),
        migrations.DeleteModel(
            name='EmprestimoParcela',
        ),
        migrations.DeleteModel(
            name='Investimento',
        ),
    ]
