# Generated by Django 4.2.6 on 2023-11-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_brand_card_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='balance',
        ),
    ]
