# Generated by Django 4.2.6 on 2023-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_investimento_id_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='razao_social',
        ),
        migrations.AddField(
            model_name='clientepj',
            name='razao_social',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
