# Generated by Django 4.2.6 on 2023-11-23 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limite de crédito do cartão', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
