# Generated by Django 4.2.6 on 2023-11-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientepf_id_cliente_clientepj_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=25)),
                ('corporate_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Business Client',
                'verbose_name_plural': 'Business Clients',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('cvv', models.CharField(max_length=5)),
                ('expiration_date', models.DateField()),
                ('brand', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.account')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='client_photos/')),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='IndividualClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Individual Client',
                'verbose_name_plural': 'Individual Clients',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField()),
                ('approved', models.BooleanField()),
                ('installment_number', models.IntegerField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.account')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_endereco',
        ),
        migrations.RemoveField(
            model_name='clientepf',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='clientepj',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='id_conta',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='id_cartao',
        ),
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClientePF',
        ),
        migrations.DeleteModel(
            name='ClientePJ',
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
    ]
